# This is a basic workflow to help you get started with Actions

name: build jar file

# Controls when the action will run.
on:
  push:
    branches:
      - main
  release:
    types: [created,published] # 表示在创建新的 Release 时触发

# Allows you to run this workflow manually from the Actions tab
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: cd app/server && mvn clean package -Dmaven.test.skip=true -DignoreSnapshots=true -Dhttps.protocols=TLSv1.2 -U
      - name: 查看jar文件
        run: ls app/server/huntly-server/target/huntly-server-*.jar